Add Miro's profile
mctantwerp/we-are-rare-2223 pull request #11
Opened 2022-10-13 21:59 UTC by miropolfliet

2022-10-17 15:09 UTC, alessandroaussems requested changes

2022-10-17 15:09 UTC, alessandroaussems commented on people/miro_polfliet.md
> +<h1>Miro Storm Polfliet</h1>
Je hebt jezelf niet toegevoegd aan de README.md? 
Je maakt ook gebruik van HTML en niet van markdown. kijk nog eens naar contributing.md

2022-10-20 18:15 UTC, miropolfliet commented on people/miro_polfliet.md
> +<h1>Miro Storm Polfliet</h1>
Gefixt! 👍

2022-10-20 18:16 UTC, miropolfliet commented
HTML veranderd naar Markdown.

2022-10-29 08:51 UTC, merged

2022-10-29 08:51 UTC, alessandroaussems commented
Top!